### PR TITLE
NOISSUE - Add further testing + make clippy recommended change

### PR DESCRIPTION
**Pull request by jmcconnell26**

### CODE REVIEW

**Comment by jmcconnell26** [comment]
Small change to add some further testing + make a clippy recommended change which had slipped through!

**Comment by anderejd** [comment]
The entire pattern feature is a copy pasted remnant from cargo-tree that I used as a starting point for cargo-geiger. I'm guessing that we can remove it. What do you think?

**Comment by jmcconnell26** [comment]
I'm not sure on this one to be honest, while it is a nice feature, I'm struggling to think of a scenario where I would use it (although that isn't necessarily a good basis to remove a feature). 
On the other hand, removing it would simplify the code base, and reduce the complexity of the program arguments.
If I had to come down on a side, I'd be tempted to leave it in, but possibly rename the argument to something along the lines of "package-display-format" to make it clearer what it's actually doing.

**Comment by anderejd** [comment]
Sure let's leave it :)

**Pull request merged**
