### PR TITLE
ISSUE-116 - Fix into target kind function logic

### PR DESCRIPTION
**Pull request by jmcconnell26**
Signed-off-by: joshmc <josh-mcc@tiscali.co.uk>

### CODE REVIEW

**Review by qrilka — APPROVED** [review]
This looks good to me but what about the comment in https://github.com/rust-secure-code/cargo-geiger/pull/194#issuecomment-788209212 ? And see my response below as well.
Maybe this should also come into this PR?

**Comment by jmcconnell26** [comment]
Thanks for taking a look!
I've just popped in a commit with a draft comment, let me know if you think it looks OK, or if there's anything you would like to change.

**Comment by jmcconnell26** [comment]
Awesome, thanks!
@anderejd does this look OK to you?

**Comment by anderejd** [comment]
@jmcconnell26 Looks good to me! Merge when you think it's ready.

**Comment by jmcconnell26** [comment]
Cheers! @qrilka, this should unblock you on https://github.com/rust-secure-code/cargo-geiger/pull/193 if you want ping me when it's ready for review?

**Comment by qrilka** [comment]
Thanks

**Pull request merged**
