### PR TITLE
Re-export public functions of the find module.

### LINKED ISSUE #203: Breaking API change introduced in v0.4.6
The refactoring of commit 897baa912af368def2607f1d05785371455eb303 created a new module (`find`) hosting the functions `find_unsafe_in_file` and `find_unsafe_in_string` of the `geiger` crate. As these functions are not re-exported in `lib.rs`, it changes the call path and requires changing imports (or the calls themselves) in dependent code.

Note that this can be easily identified by comparing the documentation of [v0.4.5](https://docs.rs/geiger/0.4.5/geiger/index.html) with the one of [v0.4.6 on docs.rs](https://docs.rs/geiger/0.4.6/geiger/index.html).

I found this issue when installing `cargo-crev` which uses this crate. 
The fix is a one-liner; I will submit it ASAP.

### PR DESCRIPTION
**Pull request by rbost**
Fixes #203

### CODE REVIEW

**Review by jmcconnell26 — COMMENTED** [review]
This looks good to me, @rbost, do you think there is any other functionality that shouldn't have been made private?

**Comment by rbost** [comment]
I don't think the code in `geiger_syn_visitor.rs` is meant to be public, and no other function from `find.rs` was public, so I don't think so.
But don't take my word for granted: I am not a real user of this crate.

**Review by jmcconnell26 — APPROVED** [review]
OK, then let's keep the accessibility of everything else the same.

**Comment by anderejd** [comment]
Should this be published as 0.4.7 or 0.5.0?

**Comment by rbost** [comment]
I has to be 0.4.7, for two reasons:
1. A minor one: it just adds features, without breaking one and hence, is a minor change (at least according to [Cargo's documentation](https://doc.rust-lang.org/cargo/reference/semver.html#minor-adding-new-public-items).
2. A major one: Cargo's dependency resolution algorithm would consider 0.4.6 and 0.5.0 as incompatible versions (see [here](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility), second paragraph), and not will not update the crate, making the API break essentially permanent unless dependent crates explicitly update the minimum required version.

**Comment by anderejd** [comment]
Thanks for the information!

0.4.7 is up https://crates.io/crates/geiger/0.4.7

**Pull request merged**
