### PR TITLE
ISSUE-175 - Add canary build without lockfile

### PR DESCRIPTION
**Pull request by jmcconnell26**

### CODE REVIEW

**Comment by anderejd** [comment]
Looks like cargo 0.47 fails for some reason. Let's try upgrading to latest cargo if you have the time?

**Comment by jmcconnell26** [comment]
Canary job working already! Taking a look at it now

**Comment by anderejd** [comment]
Ready to merge?

**Comment by jmcconnell26** [comment]
Yes, I think so! We can update the serde version to not be so strict once the new package is released.

**Pull request merged**
