### PR TITLE
ISSUE-151 - Accept Readme Path and Section Name as parameters:

### PR DESCRIPTION
**Pull request by jmcconnell26**
* Update args to accept `--readme-path` and `section-name` values
* Add logic to allow custom section names and custom README files
* Add integration test for existing readme cases
* Create new snapshots for README test cases

Signed-off-by: joshmc <josh-mcc@tiscali.co.uk>

### CODE REVIEW

**Comment by anderejd** [comment]
Should we dogfood this feature and use it for the README.md in this project as well?

**Comment by jmcconnell26** [comment]
> Should we dogfood this feature and use it for the README.md in this project as well?

Ohh, I like this idea! Let me pop it in now.

**Comment by jmcconnell26** [comment]
I had a look at this, and it looks like generating a Safety Report for `cargo-geiger` runs into the issue seen here https://github.com/rust-secure-code/cargo-geiger/issues/5
Shall we put this change on hold, and I can take a look into this issue next?

From a quick look, there seems to be two issues, one where how we handle files which are unused due to the feature flags for the dependency (like here, for serde_json-1.0.59/src/features_check/error.rs, a file which simply contains "serde_json requires that either `std` (default) or `alloc` feature is enabled"), and then an other where syn looks to fail to parse the file.

As a first step, would it be worth landing an update the `geiger` crate to use the latest version of `syn`?

Thanks,
Josh

**Comment by jmcconnell26** [comment]
Ahh, this actually looks to have been a bug I introduced with the first set of changes to write to a README.
I've raised a PR to fix here https://github.com/rust-secure-code/cargo-geiger/pull/162
The files which fail to scan for `cargo-geiger` all look to be legitimate.

Thanks,
Josh

**Comment by anderejd** [comment]
> Ahh, this actually looks to have been a bug I introduced with the first set of changes to write to a README.
I've raised a PR to fix here #162

Nice! 👍 

Waiting for a minor change in #162 before merging.

**Comment by jmcconnell26** [comment]
Hmm, I've added this, but I think it needs a bit more work to get it looking nicely.
Let me have a further look and see if I can update it to format the report better in the README.md

**Comment by jmcconnell26** [comment]
@anderejd, do you want to put this PR on hold, and let me land a separate one with a new Charset for GitHub markdown, with some better formatting for the report?

**Comment by anderejd** [comment]
> @anderejd, do you want to put this PR on hold, and let me land a separate one with a new Charset for GitHub markdown, with some better formatting for the report?

Separating it into two PRs sounds good!

**Comment by anderejd** [comment]
Ready for merge?

**Comment by jmcconnell26** [comment]
@anderejd, I've landed https://github.com/rust-secure-code/cargo-geiger/pull/163, which adds some nice formatting, and adds the nicely formatted report to the README, but I think this one is good to merge first!

Thanks,
Josh

**Pull request merged**
