### PR TITLE
NOISSUE - Add CONTRIBUTING.md file, containing a proposal for

### PR DESCRIPTION
**Pull request by jmcconnell26**
contributing to the project

### CODE REVIEW

**Comment by anderejd** [comment]
Looks good to me, let's leave this open for a while to get some feedback.

**Comment by Shnatsel** [comment]
I'm not convinced that signing commits is a good idea, since it increases the entry barrier for contributions and does not accomplish much without a solid identity management layer on top of it. I suggest making it optional rather than required.

**Comment by tarcieri** [comment]
It also provides dubious security value until git migrates away from SHA-1, which is [cryptographically broken](https://sha-mbles.github.io/).

**Comment by anderejd** [comment]
Thanks for the feedback!

I agree that the entry barrier should be low, I have added emphasis using bold styling for the following sentence: "**Pull requests are very welcome, and the below are guidelines, not rules.**"

I'll remove the point about commit signing in the document.

**Pull request merged**
