### PR TITLE
ISSUE-16 - Refactor further into separate modules, nesting several

### PR DESCRIPTION
**Pull request by jmcconnell26**
modules which are not required by the rest of the program.

* Split out several more modules from top level format module
* Split scan module into several sub modules
* Add new args module

### CODE REVIEW

**Comment by anderejd** [comment]
At a first glance this looks good to me. Let me take a closer look later today or during the weekend.

@stephaneyfx Are you currently working on anything that would be easier to merge before this PR?

**Comment by stephaneyfx** [comment]
Thank you for the heads-up @anderejd . I'm working on moving some types to the new serialization crate we discussed and defining our own `PackageId`. I skimmed through this PR and I think it should be straightforward for me to rebase my changes on top once it gets merged, so please feel free to merge it.

**Comment by anderejd** [comment]
More and smaller modules looks great! Thanks!

**Comment by jmcconnell26** [comment]
Hi @anderejd,
Thanks for the review! I'm just trying to split these PR's out and keep refactoring separate from any logic changes.Hopefully this should make the final PR easier to review.

**Pull request merged**
